######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 12 20:51:39 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT +=webkit

# Input
HEADERS += *.h
SOURCES += *.cpp
RESOURCES += htmlResources.qrc
